POST http://localhost:8888/questack-api/user HTTP/1.1
content-type: application/json
authorization:

{
  "name": "youthke2",
  "mail": "test@test.com",
  "password": "pass"
}

###

POST http://localhost:8888/questack-api/stack HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTIwMjc0NjcsImlkIjo0fQ.nh9_eLLRFHeO-TtcesDs-YV8colGmXDyO-bvOgQ8RcA

{
  "name": "好きなおでん2"
}

###

GET http://localhost:8888/questack-api/stacks HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTIwMjc0NjcsImlkIjo0fQ.nh9_eLLRFHeO-TtcesDs-YV8colGmXDyO-bvOgQ8RcA

###

POST http://localhost:8888/questack-api/stack/update HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTIwMjc0NjcsImlkIjo0fQ.nh9_eLLRFHeO-TtcesDs-YV8colGmXDyO-bvOgQ8RcA

{
  "id": 2,
  "name": "好きなおでん3"
}


###
