POST http://localhost:8888/questack-api/user HTTP/1.1
content-type: application/json
authorization:

{
  "name": "youthke2",
  "mail": "test@test.com",
  "password": "pass"
}

###

POST http://localhost:8888/questack-api/stack HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTIwMzc5ODcsImlkIjo2fQ.csTSf2tAtBSxyTaJB-3YyBbNQFpCFwzYatGaelresrQ

{
  "name": "好きなおでん22"
}

###

GET http://localhost:8888/questack-api/stacks HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTIwMjc0NjcsImlkIjo0fQ.nh9_eLLRFHeO-TtcesDs-YV8colGmXDyO-bvOgQ8RcA

###

POST http://localhost:8888/questack-api/stack/update HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTIwMjc0NjcsImlkIjo0fQ.nh9_eLLRFHeO-TtcesDs-YV8colGmXDyO-bvOgQ8RcA

{
  "id": 2,
  "name": "好きなおでん3"
}


###

POST http://localhost:8888/questack-api/sign-in HTTP/1.1
content-type: application/json
Authorization:

{
  "mail": "testaaa@test.com",
  "password": "pass"
}

###

POST http://localhost:8888/questack-api/question/create HTTP/1.1
content-type: application/json
Authorization:

{
  "stack_url": "yXXL61cqhb",
  "title": "私はたこ焼きが好き2",
  "author": "絶対匿名希望",
  "content": "aaaaaaaaaaa"
}

###